'
'****************************************************************************
'**************************** Eye of the Tiger ******************************
'****************************************************************************
'************************* From the Movie ROCKY 3 ***************************
'****************************************************************************
'
'                 Written by Frank Sullivan & Jim Peterik
'
'                   Composed for Qbasic by Jason Linett
'                            (SASEisME@aol.com)
'
' If you would like to be on my FREE Qbasic mailing, please send me E-Mail.
' There is absolutely no charge, and you get a free game or music file each
' week!!!  I mainly program music, but sometimes I do a game.  Send me
' E-Mail, I will add you to my list!!
'
'
'
'
CLS
COLOR 15, 4
LOCATE 9, 24
PRINT "                            "
LOCATE 10, 24
PRINT "      Eye of the Tiger      "
LOCATE 11, 24
PRINT "                            "
'
a$ = "g8b-10g6p6f8e-8g8f6e-8p6f8f8f6p10f8g8f6e-6p6"
b$ = "g8b-10>c6<g8f8e-8g6f6f6e-8p10c8e-10f6p10f8e-8f6f8e-10g6p6"
c$ = "g8g8b-10>c6p10<f8e-8g8f6e-8p6f8f8f8f8e-8g8f6e-6p6"
d$ = "g8g8b-10>c6p10<f8e-8g6f6f6e-8p10c8e-6f6f8e-8f8p10f8e-8g4p10"
e$ = "f6g4p10a-8a-8a-8a-6g8f8e-8e-8f8g8f8p10f6g4a-8p10a-8a-8a-8g8f8e-6g8f8f6p10"
f$ = "f6g4a-6a-8a-10a-6g8f8e-8e-8f8g8f8p10f6g4a-6g6a-6b-6a-6>c6"
g$ = "c4<p6f8e-10f6e-8e-5p5"
h$ = "c1<p6f8e-10f6e-8e-3p5"
PLAY a$
PLAY b$
PLAY c$
PLAY d$
PLAY e$
PLAY f$
PLAY g$
PLAY c$
PLAY d$
PLAY e$
PLAY f$
PLAY g$
PLAY c$
PLAY d$
PLAY e$
PLAY f$
PLAY h$

