DECLARE SUB OrderingInformation ()
DECLARE SUB AllIAskofYouReprise ()
DECLARE SUB Overture ()
DECLARE SUB ThinkofMe ()
DECLARE SUB AngelofMusic ()
DECLARE SUB TheMusicoftheNight ()
DECLARE SUB PrimaDonna ()
DECLARE SUB AllIAskofYou ()
DECLARE SUB Masquerade ()
DECLARE SUB WishingYouWereSomehowHereAgain ()
DECLARE SUB ThePointofNoReturn ()
DECLARE SUB Menu ()
DECLARE SUB ThePhantomoftheOpera ()


Menu

SUB AllIAskofYou

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""


 DO: LOOP UNTIL INKEY$ = CHR$(13)

 Menu

END SUB

SUB AllIAskofYouReprise

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""



 DO: LOOP UNTIL INKEY$ = CHR$(13)

 Menu


END SUB

SUB AngelofMusic


'----------------------------------
 CLS
 SLEEP 2
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
 SLEEP 2
'----------------------------------
 

 PRINT "MEG:"
 PRINT

 PRINT "Where in the world"
 PLAY "T70O2L8B.L16AL8GL4A"

 PRINT "have you been hiding?"
 PLAY "L8F#L4EL8AF#L4D"

 PRINT "Really, you were perfect."
 PLAY "L8B.L16AL8GL4D.L8<B>L4G"

 PRINT
 PLAY "L8CDG"

 PRINT "In only wish"
 PLAY "L8B.L16AL8GL4A"

 PRINT "I knew your secret;"
 PLAY "L8F#L4EL8AF#L4D"

 PRINT "who is this new tutor?"
 PLAY "L8B.L16AL8GL4D.L8<B>L4G."


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t

 PLAY "L4BL16AGL4AL8F#L4EL8AF#D"
 PLAY "L4BL16AGL4D.L8<B>L4GP8L8<B>D"
'----------------------------------


 PRINT "CHRISTINE:"
 PRINT

 PRINT "Father once spoke of an angel,"
 PLAY "L8GF#EDC<BB>L4E."

 PRINT "I used to dream he'd appear."
 PLAY "L8EDCC<BAL4B."

 PRINT
 PLAY "L8>AGF#"

 PRINT "Now as I sing I can sense him,"
 PLAY "L8GF#EDC<BBL4>E."

 PRINT "and I know he's here."
 PLAY "L8EF#L4G.B.L2A."

 PRINT

 PRINT "Here in this room he calls me softly,"
 PLAY "L8B.L16AL8GL4AL8F#L4EL8AF#L4D"

 PRINT "somewhere inside hiding."
 PLAY "L8B.L16AL8GL4D.L8<BL4>G"

 PLAY "L8CDG"

 PRINT "Somehow I know he's always with me;"
 PLAY "L8B.L16AL8GL4AL8F#L4EL8AF#L4D"

 PRINT "he, the unseen genius."
 PLAY "L8B.L16AL8GL4D.L8<BL4>G"

 PLAY "P8L8<B>D"


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
'----------------------------------


 PRINT "MEG:"
 PRINT

 PRINT "Christine, you must have been dreaming."
 PLAY "L8GF#EDC<BBL4>E."

 PRINT "Stories like this can't come true."
 PLAY "L8EDCC<BAL4B."

 PLAY "L8>AGF#"

 PRINT "Christine, you're talking in riddles,"
 PLAY "L8GF#EDC<BBL4>E."

 PRINT "and it's not like you."
 PLAY "L8EF#L4G.B.A.P8L8F#A"


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
'----------------------------------


 PRINT "CHRISTINE:"
 PRINT

 PRINT "Angel, I hear you!"
 PLAY "L8>D.L16CL8<B-L4>C<L8A"

 PRINT "Speak, I listen."
 PLAY "L4GL8>C<AL4F"

 PRINT "Stay by my side, guide me!"
 PLAY "L8>D.L16C<L8B-L4F.L8DL4B-."

 PRINT "Angel, my soul was weak;"
 PLAY "L8>E.L16DL8CL4D<L8BL4A"

 PRINT "forgive me!"
 PLAY "L8>D<BL4G"

 PRINT "Enter al last, master!"
 PLAY "L8E.L16DL8CL4<G.L8EL4>C"


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
 PLAY "L8P8<EG"
'----------------------------------


 PRINT "PHANTOM:"
 PRINT

 PRINT "Flattering child, you shall know me."
 PLAY "L8>C<BAGFEEL4A."

 PRINT "See why in shadow I hide."
 PLAY "L8AGFFEDL4E."

 PLAY "L8G#B>D"

 PRINT "Look at your face in the mirror!"
 PLAY "L8C<BAGFEEL4A."

 PRINT "I am there inside."
 PLAY "L8ABL4>C.E.L2D."


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
'----------------------------------


 PRINT "CHRISTINE:"
 PRINT

 PRINT "Angel of Music,"
 PLAY "L8E.L16DL8CL4DL8<B"

 PRINT "guide and guardian,"
 PLAY "L4A>L8D<BL4G"

 PRINT "grant to me your glory!"
 PLAY "L8>E.L16DL8C<L4G.L8EL4>C."

 PRINT

 PRINT "Angel of Music,"
 PLAY "L8F#.L16EL8DL4EL8C#"
 
 PRINT "hide no longer!"
 PLAY "L4<BL8>EC#<L4A"

 PRINT "Come to me, strange angel!"
 PLAY "L8>F#.L16EL8DL4<A.L8F#>L4D."


'----------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Angel of Music"

 FOR t = 1 TO 3
 PRINT
 NEXT t
'----------------------------------


 PRINT "PHANTOM:"
 PRINT
 
 PRINT "I am your Angel of Music;"
 PLAY "L4<DL8DEL4EL8DDL8DL4AP8"

 PRINT "come to me, Angel of Music!"
 PLAY "L4DL8DEL4EL8DDL8DL4AP8"

 PRINT

 PRINT "I am your Angel of Music;"
 PLAY "L4DL8DEL4EL8DDL8DL4AP8"

 PRINT "come to me, Angel of Music!"
 PLAY "L4DL8DEL4EL8DDL8DL1A."


 DO: LOOP UNTIL INKEY$ = CHR$(13)

 Menu


END SUB

SUB Masquerade

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu


END SUB

SUB Menu

CLS

LOCATE 2, 25
PRINT "The Phantom of the Opera"

FOR t = 1 TO 2
PRINT
NEXT t

PRINT "Music by ANDREW LLOYD WEBBER"
PRINT "Lyrics by CHARLES HART"
PRINT "Additional Lyrics by RICHARD STILGOE and MIKE BATT"
PRINT "(C) 1995 ORGANIZATION INC."

PRINT

COLOR 8, 0
PRINT "1.  Overture"
COLOR 7, 0
PRINT "2.  Think of Me"
PRINT "3.  Angel of Music"
COLOR 8, 0
PRINT "4.  The Phantom of the Opera"
PRINT "5.  The Music of the Night"
PRINT "6.  Prima Donna"
PRINT "7.  All I Ask of You"
PRINT "8.  All I Ask of You (Reprise)"
PRINT "9.  Masquerade"
PRINT "10. Wishing You Were Somehow Here Again"
PRINT "11. The Point of No Return"
COLOR 7, 0
PRINT "12. Ordering Information"
PRINT "13. Exit"

PRINT
INPUT "Please enter your selection: ", sele

IF sele < 1 THEN Menu
IF sele > 13 THEN Menu


IF sele = 2 THEN ThinkofMe
IF sele = 3 THEN AngelofMusic
IF sele = 4 THEN ThePhantomoftheOpera
IF sele = 5 THEN TheMusicoftheNight
IF sele = 6 THEN PrimaDonna
IF sele = 8 THEN AllIAskofYouReprise
IF sele = 7 THEN AllIAskofYou
IF sele = 9 THEN Masquerade
IF sele = 10 THEN WishingYouWereSomehowHereAgain
IF sele = 11 THEN ThePointofNoReturn
IF sele = 1 THEN Overture
IF sele = 12 THEN OrderingInformation
IF sele = 13 THEN PRINT : PRINT "Thank you for listening to The Phantom of the Opera.  Please listen again.": PRINT : END


END SUB

SUB OrderingInformation

CLS

PRINT : PRINT : PRINT

PRINT "   To order the registered version of The Phantom of the Opera"
PRINT "QMusic ver1.5, please send a self adressed stamped envelop "
PRINT "with $5.00 to:"
PRINT
PRINT "                     ORGANIZATION INC."
PRINT "                     c/o BENJAMIN KNOLL"
PRINT "                     301 EAST 300 NORTH"
PRINT "                     HYDE PARK, UT 84318 "
PRINT
PRINT "Please make checks payable to Benjamin Knoll."
PRINT
PRINT
PRINT "   With the registered version, you will recieve all of the songs "
PRINT "listed in the main menu."


DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu


END SUB

SUB Overture

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu



END SUB

SUB PrimaDonna

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu



 
END SUB

SUB TheMusicoftheNight

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu



END SUB

SUB ThePhantomoftheOpera

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu



END SUB

SUB ThePointofNoReturn

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu



END SUB

SUB ThinkofMe

'----------------------------------
 CLS
 SLEEP 2
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t
 SLEEP 2

 PLAY "T95O1L8CG>ECGCL4EP4"
 PLAY "T95O1L8CG>ECGCL4EP2"
'----------------------------------


 PRINT "CHRISTINE:"
 PRINT

 PRINT "Think of me,"
 PLAY "L8EFL4EL8P8EGC"

 PRINT "think of me fondly"
 PLAY "L8DDDL4G.D"

 PRINT "when we've said good-bye."
 PLAY "L4C.L8CL4C>CL2<GL8<B>G<B>DP4"

 PRINT "Remember me"
 PLAY "L8FEFL4EL8P8EGC"

 PRINT "once in a while"
 PLAY "L8DDDL4G.D"

 PRINT "promise me you'll try."
 PLAY "L4C.L8CL4C>CL2<G.L8<B>DFD<B>D"

 PRINT "On that day, that not so distant day,"
 PLAY "L8EFL4E.L8FEFEFL4EP8"

 PRINT "when you are far away and free,"
 PLAY "L8G#B>DL4DC<AEL2D"

 PRINT "if you ever find a moment,"
 PLAY "L4CDL8EFL2EL4AL2GE"

 PRINT "spare a thought for me."
 PLAY "L4D.E.F.<B.L2>CP8"


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t

 PLAY "L8CEG"
 PLAY "L8AB-L2A.L8GGG>L4C.<G"
 PLAY "L4F.L8FL4F>FL2C"
 PLAY "L8<EGB-GGEP8"
 PLAY "L8AB-L2A."
 PLAY "L8GGGL4>C.<L4GL4F.L8FL4F>FL2<C"
 PLAY "L8EG>C<GG"
'---------------------------------------


  PRINT "And though it's clear"
  PLAY "L8O2B-AB-L4A"
 
  PRINT "though it was always clear"
  PLAY "L8B-AB-AB-L4AP8"

  PRINT "that this was never ment to be,"
  PLAY "L8>C#EGL4GFD<AL2G"

  PRINT "if you happen to remember,"
  PLAY "L4FGL8AB-L2AL4>DL2C<A"

  PRINT "stop and think of me."
  PLAY "L4G.A.B-.E.F"


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t
 PLAY "L8O2GAL4B->C"
'---------------------------------------


  PRINT "Think of all the things"
  PLAY "L2O2<F>FL4EED"

  PRINT "we've shared and see;"
  PLAY "L4CL2>C<B-G."

  PRINT "don't think about the"
  PLAY "L4GL8AB-L2A>L4D"

  PRINT "way things might have been."
  PLAY "L2C<AGDL1E"


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t
 
'---------------------------------------
 
 
  PRINT "Think of me,"
  PLAY "L8<AB-L2A."

  PRINT "think of me waking"
  PLAY "L8GGG>L4C.<G"
  
  PRINT "silent and resigned."
  PLAY "L4F.L8FL4F>FL2C.P8"

  PRINT "Imagine me,"
  PLAY "L8<AB-L2A."

  PRINT "trying to hard"
  PLAY "L8GGG>L4C.<G"

  PRINT "to put you from my mind."
  PLAY "L4F.L8FL4F>FL2C.P8"


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t

'---------------------------------------


  PRINT "Think of me,"
  PLAY "L8<O2B-AB-L4A."
 
  PRINT "please say you'll think of me"
  PLAY "L8B-AB-AB-L4AP8"

  PRINT "whatever else you choose to do."
  PLAY "L8>C#EGL4GFD<AL2G"

  PRINT "There will never be a day"
  PLAY "L4FGL8AB-L2A>L4DL2C"

  PRINT "when I won't think of you."
  PLAY "L2<AL4G.A.B-.>E.L1F"


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t

 'Intermission
 PLAY "L8<<GGG>L4C.L4G"
 PLAY "L4F.L8FL4FL4>FL2C"
 PLAY "L8<G>CC<B-"

 PRINT "RAOUL:"
 PRINT

 PRINT "Can it be,"
 PLAY "L8<AB-L2A."

 PRINT "can it be, Christine?"
 PLAY "L8GGGL4>C.<G"

 PLAY "L4F."

 PRINT "(SPOKEN) Bravo!"
 PLAY "L8FL4F>FL2C"

 PLAY "L8<G>CC<B-"

 PRINT "What a change."
 PLAY "L8AB-L4A."

 PRINT "You're really not a bit"
 PLAY "L8B-AB-AB-L4AP8"

 PRINT "the cockish girl that once you were."
 PLAY "L8>C#EGL4GFD<AL2G"

 PRINT "She may not remember me,"
 PLAY "L4FGL8AB-L2A>L4DL2C"

 PRINT "but I remember her."
 PLAY "L2<AGAB-E"
'---------------------------------------


'----------------------------------------
 CLS
 LOCATE 2, 30
 PRINT "Think of Me"

 FOR t = 1 TO 3
 PRINT
 NEXT t
'---------------------------------------


 PRINT "CHRISTINE:"
 PRINT

 PRINT "Flowers fade,"
 PLAY "L8O2AB-L4A."

 PRINT "the fruits of summer fade,"
 PLAY "L8B-AB-AB-L4AP8"

 PRINT "they have their season, so do we."
 PLAY "L8>C#EGL4GFD<AL2G"

 PRINT "But please promise me that sometimes"
 PLAY "L4FGL8AB-L2AL4>DL2C<A"

 PRINT "you will think of me!"
 PRINT
 PRINT
 PRINT "(APPLAUSE)"
 PLAY "L2GAB->CL1F."

 
 DO: LOOP UNTIL INKEY$ = CHR$(13)


 Menu


END SUB

SUB WishingYouWereSomehowHereAgain

CLS

LOCATE 12, 1

PRINT "   To listen to this song, please select the option, 'Ordering Information'"; ""

DO: LOOP UNTIL INKEY$ = CHR$(13)

Menu


END SUB

