echo off
echo --
echo -Patty's House      326-1245
echo -Misty's House      539-3872
echo -Tracy's Beeper     354-1883
echo -Allison's Beeper   354-1894
echo -Tracy's House      326-1138
echo -Sara's House       534-4170
echo -Jennifer's House   618-9238
echo -Cassy's House      328-4645
echo -Jill's House       534-1008
echo -Danielle's House   539-8678
echo -Jeff's House       328-5675
echo -Jim's House        618-8466
echo -Kristin's House    326-8141
echo -Michelle's House   548-4311
echo -Chanel's House     603-9679
echo --
