' Coming soon...
'
'          
'            The ultimate fantasy adventue...
'                                        
'                                       
'                                         Tower of Fortune
'                                           M.R.P.G vol.1
'                                            version 1.1
'                                        unregistered version
'                                   
'
'            Tower of Fortune is the first volume,
'           from the Micro.Roll.Playing.Game series.
'
'
' Don't forget to register !!!
'

