PLAY "mn t150 o1 l4 g g g l8 e-. b-16 g4 l8 e-. b-16 g2"
PLAY "o2 l4 d d d l8 e-. o1 b-16 f+4 l8 e-. b-16 g2"
PLAY "o2 g4 o1 g8. g16 o2 g4 f+8. f16 e16 e-16 mse8 p8"
PLAY "o1 g+8 ml o2 mn c+4 c8. o1 b16 b-16 a16ms b-8 p8"
PLAY "e-8 ml f+4 mn e-8. f+16 b-4 g8. b-16 o2 d2"
PLAY "g4 o1 g8. g16 o2 g4 f+8. f16 e16 e-16 ms e8 p8"
PLAY "o1 g+8 ml o2 mn c+4 c8. o1 b16 b-16 a16 ms b-8 p8"
PLAY "e-8 ml f+4 mn e-8. b-16 g4 e-8. b-16 g2"

