'************************ Stars & Stripes Forever ***************************
'
'                           By John Philip Sousa
'
'                     Composed for Qbasic by Jason Linett
'                           (SASEisME@aol.com)
'
' If you would like to be on my FREE Qbasic mailing, please send me E-Mail.
' There is absolutely no charge, and you get a free game or music file each
' week!!!  I mainly program music, but sometimes I do a game.  Send me
' E-Mail, I will add you to my list!!
'
'                    ******* --------------
'                    ******* --------------
'                    ******* --------------    < --  Drawing of Flag
'                    ----------------------
'                    ----------------------
'                     
'
'
'
'
CLS
LOCATE 10, 27
COLOR 4, 15
PRINT "  STARS & STRIPES FOREVER  "
'
a$ = "<g6>d6<b6>d6<g6>d6<b6>d6<g6>d6<b6>d6<g3p20"
b$ = ">d4d4c6<b6b4a#6b6b2p20a#6b6b4a#6b6>d4<b6>d6c2<a3p20"
c$ = "a4a4g#6a6a4g#6a6>c2<b6a6b6>d3e3e6<a2p20"
d$ = ">d4d4c6<b6b4a#6b6b2p20a#6b6b4a#6b6>c6<b6a6f6a2g3"
e$ = "g4g4f#6g6b-4a6g6>g2<g6a6b>d6<g6a6b6>d6<d6e6b6a2g3"
PLAY a$
PLAY b$
PLAY c$
PLAY d$
PLAY e$

